# -*- coding: utf-8 -*-
"""flask_deploy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AS3ZTYdI4jcYyA4ikWMjejCaerHtGHyp
"""

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
import joblib

app = Flask(__name__)
model = joblib.load('Liver-MLP.pkl')

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    int_features = [x for x in request.form.values()]
    final_features = [np.array(int_features)]
    print(final_features)
    prediction = model.predict(final_features)

    output = prediction[0]
    print(output)

    if output == 2:
        output ='Not Affected'
    elif output == 1:
        output = 'Affected'
    
    

    return render_template('index.html', prediction_text='Liver is {}'.format(output))

if __name__ == "__main__":
    app.run(host="localhost", port=7000)



